#- ON STARTUP
# Set load-all to true if you want to load all the worlds at startup
#   If it is false then you need to run the /loadworlds command
#   You can only use true or false!
# Exclude the worlds you don't want to load at startup using the exclude line
#   Separate the worlds with a comma, use double quotes (") when a world name includes spaces
#   (Leave this blank if you don't want to exclude anything)
#   Example: - exclude ["water world","excluded"]
on startup:
- load-worlds: false
- exclude: []

#- ON COMMAND
# Exclude the worlds here you don't want to load when executing the command /loadworlds
#   Separate the worlds with a comma, use double quotes (") when a world name includes spaces
#   (Leave this blank if you don't want to exclude anything)
#   Example: - exclude ["water world","excluded"]
on command:
- exclude: []